# spring.application.name : spring boot application ?? ??
spring:
  application:
    name: front-end
  datasource:
    url: jdbc:h2:file:./board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2_console

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# server.port : ?? ?? ??
# server.servlet.encoding
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

# server.port : ?? Listen ?? ??
# server.servlet.encoding : Embedded Tomcat? ??? ??
# server.servlet.jsp.init-parameters.development : jsp ?? ? ??? ?? ?? ??
# server.shutdown
#  : Spring Boot 2.3 ?? ???? ???? ??
#  : ????? ??? ? ??? ????? ?? ??? 30?. ?? ???? ??? spring.lifecycle.timeout-per-shutdown-phase=1m ?? ?? ??
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
